language: go
sudo: false
go:
  - tip

before_install:
  - go get github.com/mattn/goveralls

notifications:
  email: false

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - $GOPATH/bin/goveralls -service=travis-ci